rename red_0.png Red_Zero.png
rename red_1.png Red_One.png
rename red_2.png Red_Two.png
rename red_3.png Red_Three.png
rename red_4.png Red_Four.png
rename red_5.png Red_Five.png
rename red_6.png Red_Six.png
rename red_7.png Red_Seven.png
rename red_8.png Red_Eight.png
rename red_9.png Red_Nine.png
rename red_picker.png Red_DrawTwo.png
rename red_reverse.png Red_Reverse.png
rename red_skip.png Red_Skip.png
rename blue_0.png Blue_Zero.png
rename blue_1.png Blue_One.png
rename blue_2.png Blue_Two.png
rename blue_3.png Blue_Three.png
rename blue_4.png Blue_Four.png
rename blue_5.png Blue_Five.png
rename blue_6.png Blue_Six.png
rename blue_7.png Blue_Seven.png
rename blue_8.png Blue_Eight.png
rename blue_9.png Blue_Nine.png
rename blue_picker.png Blue_DrawTwo.png
rename blue_reverse.png Blue_Reverse.png
rename blue_skip.png Blue_Skip.png
rename yellow_0.png Yellow_Zero.png
rename yellow_1.png Yellow_One.png
rename yellow_2.png Yellow_Two.png
rename yellow_3.png Yellow_Three.png
rename yellow_4.png Yellow_Four.png
rename yellow_5.png Yellow_Five.png
rename yellow_6.png Yellow_Six.png
rename yellow_7.png Yellow_Seven.png
rename yellow_8.png Yellow_Eight.png
rename yellow_9.png Yellow_Nine.png
rename yellow_picker.png Yellow_DrawTwo.png
rename yellow_reverse.png Yellow_Reverse.png
rename yellow_skip.png Yellow_Skip.png
rename green_0.png Green_Zero.png
rename green_1.png Green_One.png
rename green_2.png Green_Two.png
rename green_3.png Green_Three.png
rename green_4.png Green_Four.png
rename green_5.png Green_Five.png
rename green_6.png Green_Six.png
rename green_7.png Green_Seven.png
rename green_8.png Green_Eight.png
rename green_9.png Green_Nine.png
rename green_picker.png Green_DrawTwo.png
rename green_reverse.png Green_Reverse.png
rename green_skip.png Green_Skip.png
rename card_back.png Card_Back.png
rename card_back_alt.png Card_Back_Alt.png
rename wild_color_changer.png Wild_Wild.png
rename wild_pick_four.png Wild_Wild_Four.png