rename red_0_large.png Red_Zero.png
rename red_1_large.png Red_One.png
rename red_2_large.png Red_Two.png
rename red_3_large.png Red_Three.png
rename red_4_large.png Red_Four.png
rename red_5_large.png Red_Five.png
rename red_6_large.png Red_Six.png
rename red_7_large.png Red_Seven.png
rename red_8_large.png Red_Eight.png
rename red_9_large.png Red_Nine.png
rename red_picker_large.png Red_DrawTwo.png
rename red_reverse_large.png Red_Reverse.png
rename red_skip_large.png Red_Skip.png
rename blue_0_large.png Blue_Zero.png
rename blue_1_large.png Blue_One.png
rename blue_2_large.png Blue_Two.png
rename blue_3_large.png Blue_Three.png
rename blue_4_large.png Blue_Four.png
rename blue_5_large.png Blue_Five.png
rename blue_6_large.png Blue_Six.png
rename blue_7_large.png Blue_Seven.png
rename blue_8_large.png Blue_Eight.png
rename blue_9_large.png Blue_Nine.png
rename blue_picker_large.png Blue_DrawTwo.png
rename blue_reverse_large.png Blue_Reverse.png
rename blue_skip_large.png Blue_Skip.png
rename yellow_0_large.png Yellow_Zero.png
rename yellow_1_large.png Yellow_One.png
rename yellow_2_large.png Yellow_Two.png
rename yellow_3_large.png Yellow_Three.png
rename yellow_4_large.png Yellow_Four.png
rename yellow_5_large.png Yellow_Five.png
rename yellow_6_large.png Yellow_Six.png
rename yellow_7_large.png Yellow_Seven.png
rename yellow_8_large.png Yellow_Eight.png
rename yellow_9_large.png Yellow_Nine.png
rename yellow_picker_large.png Yellow_DrawTwo.png
rename yellow_reverse_large.png Yellow_Reverse.png
rename yellow_skip_large.png Yellow_Skip.png
rename green_0_large.png Green_Zero.png
rename green_1_large.png Green_One.png
rename green_2_large.png Green_Two.png
rename green_3_large.png Green_Three.png
rename green_4_large.png Green_Four.png
rename green_5_large.png Green_Five.png
rename green_6_large.png Green_Six.png
rename green_7_large.png Green_Seven.png
rename green_8_large.png Green_Eight.png
rename green_9_large.png Green_Nine.png
rename green_picker_large.png Green_DrawTwo.png
rename green_reverse_large.png Green_Reverse.png
rename green_skip_large.png Green_Skip.png
rename card_back_large.png Card_Back.png
rename card_back_alt_large.png Card_Back_Alt.png
rename wild_color_changer_large.png Wild_Wild.png
rename wild_pick_four_large.png Wild_Wild_Four.png